/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\keyboard_mouse.glb
Author: 3dzip (https://sketchfab.com/truong3dzip)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/keyboard-magic-mouse-by-apple-cfc4d70c15f34e46919588faa2ca5c43
Title: Keyboard & Magic Mouse By Apple
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function KeyboardMouse(props) {
  const { nodes, materials } = useGLTF("/models/keyboard_mouse.glb");
  const groupRef = useRef();

  useEffect(() => {
    // groupRef.current.scale.set(0.0005, 0.0005, 0.0005); // Adjust the scale here
    // groupRef.current.position.set(0.25, 0.65, 0.7); // Adjust the position here
    // groupRef.current.rotation.set(0, Math.PI, 0); // Rotate by 180 degrees
  }, []);

  return (
    <group
      position={[0.01, -0.12, 0.7]}
      rotation={[0, -Math.PI / 1, 0]}
      scale={1.1}
      {...props}
      ref={groupRef}
      dispose={null}
    >
      <group position={[0.223, 0.753, -0.01]} scale={0.001}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Mouse_Body_3DShaker}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Keyboard_body_3DShaker}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["Mouse_body_lower_3DShaker."]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Mouse_sliders_3DShaker}
        />
      </group>
      <group
        position={[0.129, 0.755, 0.06]}
        rotation={[0.117, 0, 0]}
        scale={0.001}
      >
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Keys_3DShaker}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Keyboard_body_3DShaker}
        />
      </group>
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Keyboard_body_3DShaker}
        position={[0.223, 0.753, -0.01]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.Keyboard_body_3DShaker}
        position={[0.14, 0.759, -0.046]}
        rotation={[1.574, 0, Math.PI / 2]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.Keyboard_body_3DShaker}
        position={[-0.139, 0.759, -0.046]}
        rotation={[1.574, 0, Math.PI / 2]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.Keyboard_body_3DShaker}
        position={[0.14, 0.76, -0.047]}
        rotation={[1.574, 0, Math.PI / 2]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials["Mouse_body_lower_3DShaker."]}
        position={[0.223, 0.753, -0.01]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.Mouse_sliders_3DShaker}
        position={[0.246, 0.75, 0.013]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/models/keyboard_mouse.glb");
