/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./public/models/all_setup.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Setup(props) {
  const { nodes, materials } = useGLTF("/models/all_setup.glb");
  return (
    <group {...props} dispose={null} scale={1.1} position={[0, 0, 0.1]}>
      <group position={[-0.437, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["Part5Mtl.002"]}
          position={[0.941, -0.639, 0.414]}
          rotation={[0, 0, 3.121]}
          scale={0.094}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["Part7Mtl.002"]}
          position={[0.942, -0.582, 0.132]}
          rotation={[0, 0, 3.121]}
          scale={0.094}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Part8Mtl.002"]}
          position={[0.423, -0.707, 0.601]}
          rotation={[0, 0, 3.121]}
          scale={0.094}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Union1Mtl.002"]}
          position={[0.415, -0.917, 0.672]}
          rotation={[0, 0, 3.121]}
          scale={0.094}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["Part1Mtl.002"]}
          position={[0.42, -0.8, 0.902]}
          rotation={[0, 0, 3.121]}
          scale={0.094}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Part4Mtl.002"]}
          position={[0.939, -0.712, 0.215]}
          rotation={[0, 0, 3.121]}
          scale={0.094}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Union2Mtl.002"]}
          position={[0.519, -0.717, 0.519]}
          rotation={[0, 0, 3.121]}
          scale={0.094}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Union5Mtl.002"]}
          position={[0.417, -0.788, 0.905]}
          rotation={[0, 0, 3.121]}
          scale={0.094}
        />
      </group>
      <group
        position={[0.168, 0.359, -0.064]}
        rotation={[-0.12, 0.051, -0.401]}
        scale={0.255}
      >
        <mesh
          geometry={nodes.Object_8001.geometry}
          material={materials.black_skin}
        />
        <mesh
          geometry={nodes.Object_9001.geometry}
          material={materials.outline}
        />
      </group>
      <group
        position={[0.033, 0.079, 0.051]}
        rotation={[0, -0.712, 0]}
        scale={[0.02, 0.02, 0.018]}
      >
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.black_plactic}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.outline}
        />
      </group>
      <group
        position={[0.039, 0.078, -0.005]}
        rotation={[0, 0.389, 0]}
        scale={[0.02, 0.02, 0.018]}
      >
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.black_plactic}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.outline}
        />
      </group>
      <group
        position={[-0.051, 0.078, 0]}
        rotation={[Math.PI, 0.328, 0]}
        scale={[-0.02, -0.02, -0.018]}
      >
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.black_plactic}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.outline}
        />
      </group>
      <group
        position={[-0.006, 0.078, -0.036]}
        rotation={[-Math.PI, 1.571, 0]}
        scale={[-0.02, -0.02, -0.018]}
      >
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.black_plactic}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.outline}
        />
      </group>
      <group
        position={[-0.04, 0.078, 0.054]}
        rotation={[Math.PI, -0.882, Math.PI]}
        scale={[0.02, 0.02, 0.018]}
      >
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.black_plactic}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.outline}
        />
      </group>
      <group position={[0, 0.526, 0.045]} scale={[0.154, 0.202, 0.255]}>
        <mesh
          geometry={nodes.Object_5001.geometry}
          material={materials.black_skin}
        />
        <mesh
          geometry={nodes.Object_6001.geometry}
          material={materials.outline}
        />
      </group>
      <group position={[0.245, 0.34, 0.148]} scale={[0.012, 0.006, 0.017]}>
        <mesh
          geometry={nodes.Object_44.geometry}
          material={materials.black_skin}
        />
        <mesh geometry={nodes.Object_45.geometry} material={materials.metal} />
      </group>
      <group position={[0.245, 0.584, 0.166]} scale={[0.169, 0.255, 0.266]}>
        <mesh
          geometry={nodes.Object_58.geometry}
          material={materials.black_skin}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.outline}
        />
      </group>
      <group
        position={[-0.006, 0.774, -0.178]}
        rotation={[1.605, 0, 0]}
        scale={[0.132, 0.143, 0.096]}
      >
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials.black_skin}
        />
        <mesh
          geometry={nodes.Object_52.geometry}
          material={materials.outline}
        />
      </group>
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.black_skin}
        position={[-0.008, 0.571, -0.129]}
        rotation={[-0.208, 0, 0]}
        scale={[0.119, 0.115, 0.093]}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.black_plactic}
        position={[-0.005, 0.077, 0.016]}
        rotation={[0, -0.343, 0]}
        scale={[0.061, 0.034, 0.061]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.black_plactic}
        position={[-0.131, 0.291, 0.074]}
        rotation={[Math.PI, -0.452, Math.PI]}
        scale={[0.36, 0.412, 0.36]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.black_plactic}
        position={[-0.191, 0.016, 0.238]}
        rotation={[Math.PI / 2, 0, -0.876]}
        scale={0.283}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.black_plactic}
        position={[0.214, 0.018, 0.206]}
        rotation={[-Math.PI / 2, 0, -0.73]}
        scale={-0.283}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.black_plactic}
        position={[0.265, 0.016, -0.098]}
        rotation={[-Math.PI / 2, 0, 0.435]}
        scale={-0.283}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.black_plactic}
        position={[-0.006, 0.016, -0.276]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={-0.283}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.black_plactic}
        position={[-0.275, 0.016, -0.077]}
        rotation={[Math.PI / 2, 0, 0.315]}
        scale={0.283}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.black_plactic}
        position={[-0.004, 0.141, 0.015]}
        scale={0.028}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials.black_plactic}
        position={[-0.004, 0.313, 0.117]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.637, 1.063, 1.063]}
      />
      <mesh
        geometry={nodes.Object_47.geometry}
        material={materials.black_plactic}
        position={[-0.004, 0.275, 0.178]}
        rotation={[3.129, 0, Math.PI]}
        scale={[1.063, 0.907, 1.004]}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.black_skin}
        position={[0.06, 0.922, -0.221]}
        rotation={[1.525, 0, 0]}
        scale={[0.038, 0.034, 0.038]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials["Material.002"]}
        position={[-0.005, 0.883, -0.189]}
        rotation={[1.381, 0, 0]}
        scale={[0.118, 0.087, 0.079]}
      />
      <mesh
        geometry={nodes.Object_61.geometry}
        material={materials["Material.001"]}
        position={[0.191, 0.356, -0.113]}
        rotation={[-0.123, 0.177, -1.528]}
        scale={0.013}
      />
      <mesh
        geometry={nodes.Object_63.geometry}
        material={materials["Material.001"]}
        position={[0.187, 0.356, -0.113]}
        rotation={[-0.119, 0.179, -1.549]}
        scale={0.013}
      />
      <mesh
        geometry={nodes.Object_65.geometry}
        material={materials["Material.001"]}
        position={[0.187, 0.356, -0.113]}
        rotation={[-0.119, 0.179, -1.549]}
        scale={0.013}
      />
      <mesh
        geometry={nodes.Object_67.geometry}
        material={materials["Material.001"]}
        position={[0.196, 0.356, -0.114]}
        rotation={[-0.119, 0.179, -1.549]}
        scale={0.013}
      />
      <mesh
        geometry={nodes.Object_69.geometry}
        material={materials["Material.001"]}
        position={[-0.19, 0.525, -0.13]}
        rotation={[-0.126, 0.075, -1.481]}
        scale={0.013}
      />
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials["Material.001"]}
        position={[0.196, 0.356, -0.114]}
        rotation={[-0.119, 0.179, -1.549]}
        scale={0.013}
      />
      <mesh
        geometry={nodes.Object_73.geometry}
        material={materials.outline}
        position={[0.07, 0.585, -0.074]}
        rotation={[1.293, 0, 0]}
        scale={[0.019, 0.079, 0.079]}
      />
      <mesh
        geometry={nodes.Object_75.geometry}
        material={materials.black_skin}
        position={[-0.005, 0.885, -0.24]}
        rotation={[1.502, 0, 0]}
        scale={0.008}
      />
      <mesh
        geometry={nodes.Object_77.geometry}
        material={materials.outline}
        position={[-0.005, 0.883, -0.189]}
        rotation={[1.381, 0, 0]}
        scale={[0.118, 0.087, 0.08]}
      />
      <mesh
        geometry={nodes.Object_79.geometry}
        material={materials.outline}
        position={[-0.051, 1.041, -0.205]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.038}
      />
      <group position={[0, -0.129, 0.55]} rotation={[-Math.PI / 2, 0, 3.085]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.129, 0.755, 0.06]}
            rotation={[0.117, 0, 0]}
            scale={0.001}
          >
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials.Keyboard_body_3DShaker}
            />
            <mesh
              geometry={nodes.Object_9002.geometry}
              material={materials.Keys_3DShaker}
            />
          </group>
          <group position={[0.223, 0.753, -0.01]} scale={0.001}>
            <mesh
              geometry={nodes.Object_4001.geometry}
              material={materials.Mouse_Body_3DShaker}
            />
            <mesh
              geometry={nodes.Object_5002.geometry}
              material={materials.Keyboard_body_3DShaker}
            />
            <mesh
              geometry={nodes.Object_6002.geometry}
              material={materials["Mouse_body_lower_3DShaker."]}
            />
            <mesh
              geometry={nodes.Object_7001.geometry}
              material={materials.Mouse_sliders_3DShaker}
            />
          </group>
          <mesh
            geometry={nodes.Object_14001.geometry}
            material={materials.Keyboard_body_3DShaker}
            position={[0.14, 0.759, -0.046]}
            rotation={[1.574, 0, Math.PI / 2]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_16001.geometry}
            material={materials.Keyboard_body_3DShaker}
            position={[-0.139, 0.759, -0.046]}
            rotation={[1.574, 0, Math.PI / 2]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.Keyboard_body_3DShaker}
            position={[0.14, 0.76, -0.047]}
            rotation={[1.574, 0, Math.PI / 2]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_20001.geometry}
            material={materials["Mouse_body_lower_3DShaker."]}
            position={[0.223, 0.753, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.Keyboard_body_3DShaker}
            position={[0.223, 0.753, -0.01]}
            scale={0.001}
          />
          <mesh
            geometry={nodes.Object_22001.geometry}
            material={materials.Mouse_sliders_3DShaker}
            position={[0.246, 0.75, 0.013]}
            rotation={[-Math.PI, 0, 0]}
            scale={0.001}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/all_setup.glb");
