name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          port: ${{ secrets.HETZNER_PORT }}
          script: |
            git clone git@github.com:smadixd/mohammadalsmadi.git || git -C mohammadalsmadi pull origin main
            cd mohammadalsmadi
            git checkout main
            sudo docker build \
            --build-arg VITE_SERVICE_KEY=${{ secrets.VITE_SERVICE_KEY }} \
            --build-arg VITE_TEMPLATE_ID=${{ secrets.VITE_TEMPLATE_ID }} \
            --build-arg VITE_PUBLIC_KEY=${{ secrets.VITE_PUBLIC_KEY }} \
            --build-arg VITE_LITLY_PROJECT_ID=${{ secrets.VITE_LITLY_PROJECT_ID }} \
            --build-arg VITE_GITHUB_TOKEN=${{ secrets.VITE_GITHUB_TOKEN }} \
            -t portfolio .
            sudo docker stop portfolio-container || true
            sudo docker rm portfolio-container || true
            sudo docker run -d --name portfolio-container -p 127.0.0.1:5000:5000 --network my-network portfolio

      - name: Clear cache
        run: |
          sudo docker system prune -af
