name: Deploy

on:
  push:
    branches:
      - removed-3d-model

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            git clone git@github.com:smadixd/my-portfolio.git || git -C my-portfolio pull origin removed-3d-model
            cd my-portfolio
            git checkout removed-3d-model
            docker build -t portfolio .
            docker stop portfolio-container || true
            docker rm portfolio-container || true
            docker run -d --name portfolio-container -p 127.0.0.1:5000:5000 portfolio
            docker network connect my-network portfolio-container || true
